on: push

env:
  PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
  PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - run: curl -LO https://github.com/czy-29/workflow-bin/releases/latest/download/workflow-bin
    - run: chmod +x workflow-bin
    - run: ./workflow-bin start
    - uses: actions/checkout@v4
    - run: curl -LO https://github.com/czy-29/workflow-bin/releases/latest/download/workflow-bin
    - run: chmod +x workflow-bin
    - run: ./workflow-bin run
