on:
  push:
  schedule:
    - cron: '30 8 * * *'

env:
  PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
  PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
  HUGO_DRAFT_BASE_URL: ${{ secrets.HUGO_DRAFT_BASE_URL }}
  DEPLOY_GITHUB_ACCESS_TOKEN: ${{ secrets.DEPLOY_GITHUB_ACCESS_TOKEN }}
  OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
  OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
  OSS_DRAFT_BUCKET: ${{ secrets.OSS_DRAFT_BUCKET }}
  OSS_DRAFT_ENDPOINT: ${{ secrets.OSS_DRAFT_ENDPOINT }}
  OSS_PROD_BUCKET: ${{ secrets.OSS_PROD_BUCKET }}
  OSS_PROD_ENDPOINT: ${{ secrets.OSS_PROD_ENDPOINT }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - run: curl -LO https://github.com/czy-29/workflow-bin/releases/latest/download/workflow-bin
    - run: chmod +x workflow-bin
    - run: ./workflow-bin start
    - uses: actions/checkout@v4
    - run: curl -LO https://github.com/czy-29/workflow-bin/releases/latest/download/workflow-bin
    - run: chmod +x workflow-bin
    - run: ./workflow-bin run
