on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: curl -LO https://github.com/czy-29/29bot.com/releases/download/workflow-bin-v5/workflow-bin
    - run: chmod +x workflow-bin
    - run: ./workflow-bin help
